'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Download, Loader2, FileDown } from 'lucide-react'
import { 
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'

type DownloadButtonProps = {
  documentId: number
  documentTitle: string
  documentContent: string
}

export function DownloadButton({ documentId, documentTitle, documentContent }: DownloadButtonProps) {
  const [isDownloading, setIsDownloading] = useState(false)

  const handleDownloadPDF = async () => {
    setIsDownloading(true)
    
    try {
      // Dynamically import jsPDF to avoid SSR issues
      const { jsPDF } = await import('jspdf')
      
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      })

      // Set up document styling
      const pageWidth = doc.internal.pageSize.getWidth()
      const pageHeight = doc.internal.pageSize.getHeight()
      const margin = 25
      const maxWidth = pageWidth - (margin * 2)
      let yPosition = margin

      // Add watermark/logo text at top
      doc.setFontSize(10)
      doc.setTextColor(100, 100, 100)
      doc.text('Letterise', pageWidth - margin, 15, { align: 'right' })

      // Add title
      yPosition += 10
      doc.setFontSize(14)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(0, 0, 0)
      doc.text(documentTitle, margin, yPosition)
      yPosition += 10

      // Add date
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(80, 80, 80)
      const currentDate = new Date().toLocaleDateString('en-GB', { 
        day: 'numeric', 
        month: 'long', 
        year: 'numeric' 
      })
      doc.text(`Generated: ${currentDate}`, margin, yPosition)
      yPosition += 15

      // Add content
      doc.setFontSize(11)
      doc.setFont('times', 'normal')
      doc.setTextColor(0, 0, 0)

      const lines = doc.splitTextToSize(documentContent, maxWidth)
      
      lines.forEach((line: string) => {
        // Check if we need a new page
        if (yPosition > pageHeight - 40) {
          doc.addPage()
          yPosition = margin
        }
        
        doc.text(line, margin, yPosition)
        yPosition += 6
      })

      // Add footer/disclaimer on last page
      const disclaimerY = pageHeight - 30
      doc.setFontSize(8)
      doc.setTextColor(100, 100, 100)
      doc.setFont('helvetica', 'italic')
      
      const disclaimer = 'Legal Disclaimer: This document was generated by Letterise and does not constitute legal advice. For legal matters, please consult a licensed attorney or solicitor.'
      const disclaimerLines = doc.splitTextToSize(disclaimer, maxWidth)
      
      let disclaimerYPos = disclaimerY
      disclaimerLines.forEach((line: string) => {
        doc.text(line, margin, disclaimerYPos)
        disclaimerYPos += 4
      })

      // Add page numbers
      const pageCount = doc.getNumberOfPages()
      doc.setFontSize(8)
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.text(
          `Page ${i} of ${pageCount}`,
          pageWidth - margin,
          pageHeight - 10,
          { align: 'right' }
        )
      }

      // Save the PDF
      doc.save(`${documentTitle.replace(/[^a-z0-9]/gi, '_')}.pdf`)
    } catch (error) {
      console.error('[v0] PDF generation error:', error)
      alert('Failed to generate PDF. Please try again.')
    } finally {
      setIsDownloading(false)
    }
  }

  const handleDownloadHTML = async () => {
    setIsDownloading(true)
    
    try {
      const response = await fetch('/api/export-pdf', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ documentId })
      })

      if (!response.ok) {
        throw new Error('Failed to download document')
      }

      const blob = await response.blob()
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${documentTitle.replace(/[^a-z0-9]/gi, '_')}.html`
      document.body.appendChild(a)
      a.click()
      window.URL.revokeObjectURL(url)
      document.body.removeChild(a)
    } catch (error) {
      console.error('[v0] Download error:', error)
      alert('Failed to download document. Please try again.')
    } finally {
      setIsDownloading(false)
    }
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button disabled={isDownloading}>
          {isDownloading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Downloading...
            </>
          ) : (
            <>
              <Download className="mr-2 h-4 w-4" />
              Download
            </>
          )}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={handleDownloadPDF}>
          <FileDown className="mr-2 h-4 w-4" />
          Download as PDF
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleDownloadHTML}>
          <Download className="mr-2 h-4 w-4" />
          Download as HTML
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
