import { requireAuth } from '@letterise/lib/auth'
import { sql } from '@letterise/lib/db'
import { NextResponse } from 'next/server'

export async function POST(req: Request) {
  try {
    const user = await requireAuth()
    const { documentId } = await req.json()

    // Verify document belongs to user
    const documents = await sql`
      SELECT * FROM documents
      WHERE id = ${documentId} AND user_id = ${user.id}
    `

    if (documents.length === 0) {
      return NextResponse.json(
        { error: 'Document not found' },
        { status: 404 }
      )
    }

    const document = documents[0]

    const generatedDate = new Date().toLocaleDateString('en-GB', {
      day: 'numeric',
      month: 'long',
      year: 'numeric'
    })

    const formattedContent = document.content
      .split(/\n\s*\n/)
      .map((block: string) => block.trim())
      .filter(Boolean)
      .map((block: string) => {
        if (/^[A-Z][A-Z\s\-]{2,}$/.test(block)) {
          return `<h2>${block}</h2>`
        }

        if (/^(Date|Subject|To|From|Re):/i.test(block)) {
          return `<p class=\"meta-line\"><strong>${block}</strong></p>`
        }

        if (/^(Sincerely|Yours faithfully|Best regards|Regards|Respectfully),?$/i.test(block)) {
          return `<p class=\"closing\">${block}</p>`
        }

        return `<p>${block.replace(/\n/g, '<br>')}</p>`
      })
      .join('')

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${document.title}</title>
  <style>
    @page {
      margin: 1in;
      size: A4;
    }
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: 'Inter', 'Segoe UI', 'Calibri', sans-serif;
      font-size: 11pt;
      line-height: 1.7;
      color: #111827;
      max-width: 100%;
      background: white;
      padding: 0;
    }
    .document-container {
      max-width: 8.25in;
      margin: 0 auto;
      padding: 0.85in 0.9in;
      background: white;
      border: 1px solid #e5e7eb;
      border-radius: 12px;
    }
    .header {
      margin-bottom: 1.5em;
      padding-bottom: 0.9em;
      border-bottom: 1px solid #d1d5db;
    }
    .title {
      font-family: 'Georgia', 'Times New Roman', serif;
      font-size: 20pt;
      font-weight: 700;
      line-height: 1.2;
      color: #0f172a;
      margin-bottom: 0.2em;
    }
    .subtitle {
      font-size: 9pt;
      letter-spacing: 0.04em;
      text-transform: uppercase;
      color: #6b7280;
    }
    .content {
      text-align: left;
      margin-bottom: 2.4em;
    }
    .content p {
      margin: 0.9em 0;
      text-align: justify;
      text-justify: inter-word;
    }
    .content h2 {
      margin: 1.6em 0 0.6em;
      font-family: 'Georgia', 'Times New Roman', serif;
      font-size: 13.5pt;
      color: #1f2937;
      letter-spacing: 0.01em;
    }
    .meta-line {
      margin: 0.35em 0 !important;
      color: #1f2937;
      text-align: left !important;
    }
    .closing {
      margin-top: 1.6em !important;
      text-align: left !important;
    }
    .footer {
      margin-top: 2.8em;
      padding-top: 1em;
      border-top: 1px solid #d1d5db;
      font-size: 8.5pt;
      color: #6b7280;
      text-align: center;
      line-height: 1.5;
    }
    .watermark {
      position: fixed;
      bottom: 0.5in;
      right: 0.5in;
      font-size: 8pt;
      color: #9ca3af;
      opacity: 0.7;
    }
    @media print {
      body {
        padding: 0;
        margin: 0;
      }
      .no-print {
        display: none;
      }
    }
  </style>
</head>
<body>
  <div class="document-container">
    <div class="header">
      <h1 class="title">${document.title}</h1>
      <p class="subtitle">Generated Document • Letterise</p>
    </div>
    <div class="content">${formattedContent}</div>
    <div class="footer">
      <p><strong>Legal Disclaimer:</strong> This document was generated by Letterise and does not constitute legal advice.</p>
      <p>For legal matters, please consult a licensed attorney or solicitor.</p>
      <p style="margin-top: 0.5em; font-size: 8pt;">Generated on ${generatedDate} • Letterise.com</p>
    </div>
  </div>
</body>
</html>
    `

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="${document.title.replace(/[^a-z0-9]/gi, '_')}.html"`,
      },
    })
  } catch (error: any) {
    console.error('[v0] PDF export error:', error)
    
    if (error.message === 'Unauthorized') {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    return NextResponse.json(
      { error: 'Failed to export document' },
      { status: 500 }
    )
  }
}
