import { Header } from '@letterise/components/header'
import { Footer } from '@letterise/components/footer'
import { Card, CardContent } from '@letterise/components/ui/card'
import { Alert, AlertDescription } from '@letterise/components/ui/alert'
import { Shield, AlertTriangle } from 'lucide-react'

export default function DisclaimerPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      
      <main className="flex-1">
        <section className="border-b bg-muted/50">
          <div className="container py-12">
            <h1 className="text-4xl font-bold mb-2">Legal Disclaimer</h1>
            <p className="text-muted-foreground">Important information about using Letterise</p>
          </div>
        </section>

        <div className="container py-12 max-w-4xl">
          <Alert className="mb-8 border-destructive/50 bg-destructive/5">
            <AlertTriangle className="h-5 w-5 text-destructive" />
            <AlertDescription className="text-base">
              <strong>CRITICAL NOTICE:</strong> Letterise is an AI-powered document generation tool and does NOT provide legal advice. 
              The information and documents generated by this service are for informational purposes only.
            </AlertDescription>
          </Alert>

          <Card>
            <CardContent className="p-8 prose max-w-none">
              <section>
                <h2>1. No Attorney-Client Relationship</h2>
                <p className="font-semibold text-lg">
                  Using Letterise does NOT create an attorney-client relationship.
                </p>
                <p>
                  Letterise is a technology platform that uses artificial intelligence to generate documents based on templates 
                  and user-provided information. We are not a law firm, and our Service does not provide legal advice, opinions, 
                  or recommendations about your legal rights, remedies, defenses, options, or strategies.
                </p>
                <p>
                  <strong>For legal matters, you should consult with a licensed attorney in your jurisdiction.</strong>
                </p>
              </section>

              <section>
                <h2>2. Template-Based Document Generation</h2>
                <p>
                  All documents generated by Letterise are based on general templates and your specific inputs. These documents:
                </p>
                <ul>
                  <li>Are created using AI and may contain errors or inaccuracies</li>
                  <li>May not be suitable for your specific legal situation</li>
                  <li>Should be reviewed by a qualified attorney before use</li>
                  <li>May not comply with all jurisdictional requirements</li>
                  <li>Are provided "as is" without warranties of any kind</li>
                </ul>
              </section>

              <section>
                <h2>3. No Guarantee of Legal Validity</h2>
                <p>
                  We make NO guarantees or warranties regarding:
                </p>
                <ul>
                  <li>The legal validity or enforceability of generated documents</li>
                  <li>The accuracy or completeness of document content</li>
                  <li>The suitability of documents for your specific situation</li>
                  <li>Compliance with laws in your jurisdiction</li>
                  <li>The outcome of any legal matter involving generated documents</li>
                </ul>
                <p className="font-semibold">
                  Laws vary by jurisdiction and change frequently. Generated documents may not reflect the most current legal 
                  standards or requirements in your area.
                </p>
              </section>

              <section>
                <h2>4. User Responsibility</h2>
                <p>
                  You are solely responsible for:
                </p>
                <ul>
                  <li>Reviewing all generated documents for accuracy and completeness</li>
                  <li>Ensuring information you provide is accurate and truthful</li>
                  <li>Verifying that documents meet your specific needs</li>
                  <li>Consulting with legal counsel before using documents in legal matters</li>
                  <li>Understanding and complying with applicable laws</li>
                  <li>Any consequences resulting from use of generated documents</li>
                </ul>
              </section>

              <section>
                <h2>5. AI-Generated Content Limitations</h2>
                <p>
                  Letterise uses artificial intelligence (AI) to generate documents. AI technology:
                </p>
                <ul>
                  <li>May produce errors, inconsistencies, or inaccurate information</li>
                  <li>Cannot replace human judgment or legal expertise</li>
                  <li>May not understand nuances of complex legal situations</li>
                  <li>Should not be relied upon as the sole source for legal documents</li>
                </ul>
                <p>
                  Always review AI-generated content carefully and seek professional advice when needed.
                </p>
              </section>

              <section>
                <h2>6. Jurisdictional Limitations</h2>
                <p>
                  Legal requirements vary significantly by:
                </p>
                <ul>
                  <li>Country, state, province, and local jurisdiction</li>
                  <li>Type of legal matter</li>
                  <li>Specific circumstances of your situation</li>
                </ul>
                <p>
                  Letterise cannot account for all variations in law across different jurisdictions. Documents may require 
                  modification to comply with local laws and regulations.
                </p>
              </section>

              <section>
                <h2>7. Not a Substitute for Legal Counsel</h2>
                <p className="font-semibold text-lg">
                  Letterise is NOT a substitute for personalized legal advice from a qualified attorney.
                </p>
                <p>
                  If you have questions about your legal rights or options, face legal action, need to file legal documents, 
                  or are involved in a dispute, you should consult with a licensed attorney who can:
                </p>
                <ul>
                  <li>Understand your specific situation</li>
                  <li>Provide advice tailored to your needs</li>
                  <li>Represent your interests</li>
                  <li>Ensure compliance with applicable laws</li>
                </ul>
              </section>

              <section>
                <h2>8. Disclaimer of Warranties</h2>
                <p>
                  THE SERVICE AND ALL GENERATED DOCUMENTS ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, 
                  EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:
                </p>
                <ul>
                  <li>Warranties of merchantability</li>
                  <li>Fitness for a particular purpose</li>
                  <li>Non-infringement</li>
                  <li>Accuracy or completeness</li>
                  <li>Legal validity or effectiveness</li>
                </ul>
              </section>

              <section>
                <h2>9. Limitation of Liability</h2>
                <p>
                  TO THE MAXIMUM EXTENT PERMITTED BY LAW, LETTERISE AND ITS AFFILIATES SHALL NOT BE LIABLE FOR ANY:
                </p>
                <ul>
                  <li>Legal consequences arising from use of generated documents</li>
                  <li>Losses, damages, or expenses related to legal matters</li>
                  <li>Adverse outcomes in disputes, claims, or legal proceedings</li>
                  <li>Errors, omissions, or inaccuracies in generated content</li>
                  <li>Direct, indirect, incidental, consequential, or punitive damages</li>
                </ul>
                <p>
                  You use the Service at your own risk.
                </p>
              </section>

              <section>
                <h2>10. Confidentiality Notice</h2>
                <p>
                  Communications through Letterise are NOT protected by attorney-client privilege. Information you provide:
                </p>
                <ul>
                  <li>May be stored and processed by third-party AI services</li>
                  <li>Is subject to our Privacy Policy</li>
                  <li>Should not include highly sensitive or confidential information</li>
                </ul>
                <p>
                  For confidential legal matters, consult directly with an attorney.
                </p>
              </section>

              <section>
                <h2>11. Specific Document Type Disclaimers</h2>
                
                <h3>Dispute Letters</h3>
                <p>
                  Dispute letters should be reviewed for compliance with relevant consumer protection laws and debt collection 
                  regulations in your jurisdiction.
                </p>

                <h3>Insurance Claims</h3>
                <p>
                  Insurance claim letters should be reviewed for compliance with policy terms and insurance regulations. 
                  Consult with an attorney or insurance professional for complex claims.
                </p>

                <h3>Complaint Letters</h3>
                <p>
                  Complaint letters should accurately represent facts and comply with defamation and harassment laws.
                </p>

                <h3>Appeals</h3>
                <p>
                  Appeal letters may be subject to strict deadlines, formatting requirements, and procedural rules. 
                  Consult with an attorney to ensure compliance.
                </p>

                <h3>Official Documents</h3>
                <p>
                  Requests for official documents (e.g., FOIA requests) must comply with specific legal requirements and 
                  procedures. Consult with an attorney familiar with relevant laws.
                </p>
              </section>

              <section>
                <h2>12. Updates and Changes</h2>
                <p>
                  This disclaimer may be updated from time to time. Your continued use of the Service constitutes acceptance 
                  of any changes.
                </p>
              </section>

              <section>
                <h2>13. Acknowledgment</h2>
                <p className="font-semibold">
                  BY USING LETTERISE, YOU ACKNOWLEDGE THAT:
                </p>
                <ul>
                  <li>You have read and understood this disclaimer</li>
                  <li>You understand the Service does not provide legal advice</li>
                  <li>You will not rely on generated documents without legal review</li>
                  <li>You accept full responsibility for use of generated documents</li>
                  <li>You will consult with an attorney for legal matters</li>
                </ul>
              </section>

              <section>
                <h2>14. Contact Information</h2>
                <p>
                  For questions about this disclaimer or the Service:
                </p>
                <p>
                  Email: legal@letterise.com
                </p>
                <p className="font-semibold">
                  This email is for administrative purposes only and does not establish an attorney-client relationship.
                </p>
              </section>
            </CardContent>
          </Card>

          <Alert className="mt-8 border-primary/50 bg-primary/5">
            <Shield className="h-5 w-5 text-primary" />
            <AlertDescription>
              <strong>Need Legal Advice?</strong> If you need legal advice or representation, please consult with a licensed 
              attorney in your jurisdiction. Many bar associations offer lawyer referral services to help you find qualified counsel.
            </AlertDescription>
          </Alert>
        </div>
      </main>

      <Footer />
    </div>
  )
}
