// PDF generation utilities for creating professionally formatted documents
export function generatePDFContent(content: string, title: string, date: string) {
  // Parse the content to extract different sections
  const lines = content.split('\n').filter(line => line.trim() !== '')
  
  return {
    lines,
    metadata: {
      title,
      date,
      disclaimer: 'This document was generated by Letterise and does not constitute legal advice. For legal matters, please consult a licensed attorney or solicitor.'
    }
  }
}

export function formatDateUK(date: Date): string {
  return date.toLocaleDateString('en-GB', { 
    day: 'numeric', 
    month: 'long', 
    year: 'numeric' 
  })
}
